### Adversarial SuperstarGAN: Performance Evaluation & Metrics

In [1]:
import json
import pandas as pd

In [2]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

In [3]:
arguments_log = "logs/arguments_log.json"

with open(arguments_log, "r") as file:
    logs = json.load(file)

df_arguments = pd.DataFrame(logs)

# Move "id" to the first column index.
if "id" in df_arguments.columns:
    cols = ["id"] + [col for col in df_arguments.columns if col != "id"]
    df_arguments = df_arguments[cols]

display(df_arguments)

,id,training_session,c_dim,crop_size,image_size,g_conv_dim,d_conv_dim,c_conv_dim,g_repeat_num,d_repeat_num,c_repeat_num,lambda_cls,lambda_rec,lambda_gp,lambda_perturbation,nadir_slack,disc_weights,dataset,batch_size,num_iters,num_iters_decay,g_lr,d_lr,c_lr,n_critic,beta1,beta2,c_beta1,resume_iters,selected_attrs,test_iters,num_workers,mode,use_tensorboard,attr_path,imagenet_image_dir,log_dir,model_save_dir,sample_dir,result_dir,log_step,sample_step,model_save_step,lr_update_step
0,1,2025-02-03 14:28:33,2,178,128,8,8,8,6,6,6,0.25,1.3,1,0.9,1.1,"[0.7, 0.3]",ImageNet,6,500000,100000,0.0001,0.0001,0.00012,5,0.0,0.999,0.9,None,"[original, perturbation]",500000,0,train,False,../../Datasets/ImageNet5/image_data.txt,../../Datasets/ImageNet5/Images,logs/imagenet,models/imagenet,samples/imagenet,results/imagenet,10,1000,10000,1000
1,2,2025-02-03 14:52:49,2,178,128,8,8,8,6,6,6,0.25,1.3,1,0.9,1.1,"[0.7, 0.3]",ImageNet,6,500000,100000,0.0001,0.0001,0.00012,5,0.0,0.999,0.9,None,"[original, perturbation]",500000,0,train,False,../../Datasets/ImageNet5/image_data.txt,../../Datasets/ImageNet5/Images,logs/imagenet,models/imagenet,samples/imagenet,results/imagenet,10,1000,10000,1000

In [4]:
df_arguments.to_csv("logs/arguments_log.csv", index=False)
print("[ INFO ] CSV file saved successfully.")

[ INFO ] CSV file saved successfully.

In [5]:
classification_log = "logs/classification_log.json"

with open(classification_log, "r") as file:
    logs = json.load(file)

df_classification = pd.DataFrame(logs)

# Move "id" to the first column index.
if "id" in df_classification.columns:
    cols = ["id"] + [col for col in df_classification.columns if col != "id"]
    df_classification = df_classification[cols]
    
df_classification.head()

,id,classification_session,validation_images,adversarial_images,fooled_images,original_accuracy,adversarial_accuracy,fid,lpips
0,1,2025-01-30 11:50:01,1999,1602,495,80.14,30.90,153.76,0.73
1,2,2025-01-29 11:50:01,1999,1602,281,80.14,17.54,164.42,0.98

In [6]:
# Get the "id" with the highest the "adversarial_accuracy"
df_classification[df_classification['adversarial_accuracy']==df_classification['adversarial_accuracy'].max()]

,id,classification_session,validation_images,adversarial_images,fooled_images,original_accuracy,adversarial_accuracy,fid,lpips
0,1,2025-01-30 11:50:01,1999,1602,495,80.14,30.9,153.76,0.73

In [7]:
df_classification.to_csv("logs/classification_log.csv", index=False)
print("[ INFO ] CSV file saved successfully.")

[ INFO ] CSV file saved successfully.